[2022-03-11 18:52:41,040] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_04 manual__2022-01-14T20:51:26.443113+00:00 [queued]>
[2022-03-11 18:52:41,390] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_04 manual__2022-01-14T20:51:26.443113+00:00 [queued]>
[2022-03-11 18:52:41,402] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-11 18:52:41,403] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-03-11 18:52:41,403] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-11 18:52:41,630] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): task_04> on 2022-01-14 20:51:26.443113+00:00
[2022-03-11 18:52:41,678] {standard_task_runner.py:52} INFO - Started process 5163 to run task
[2022-03-11 18:52:41,807] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_04', 'manual__2022-01-14T20:51:26.443113+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmp49tda14v', '--error-file', '/tmp/tmpc5jjnr0s']
[2022-03-11 18:52:41,846] {standard_task_runner.py:77} INFO - Job 69: Subtask task_04
[2022-03-11 18:52:43,438] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_04 manual__2022-01-14T20:51:26.443113+00:00 [running]> on host airflowvm
[2022-03-11 18:52:44,890] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_04
AIRFLOW_CTX_EXECUTION_DATE=2022-01-14T20:51:26.443113+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-14T20:51:26.443113+00:00
[2022-03-11 18:52:44,891] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-11 18:52:44,891] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-03-11 18:52:45,249] {subprocess.py:85} INFO - Output:
[2022-03-11 18:52:48,332] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-11 18:52:49,496] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_04, execution_date=20220114T205126, start_date=20220311T185241, end_date=20220311T185249
[2022-03-11 18:52:49,677] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-11 18:52:50,108] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
