[2022-01-14 20:51:23,299] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_01 scheduled__2022-01-13T00:00:00+00:00 [queued]>
[2022-01-14 20:51:23,688] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_01 scheduled__2022-01-13T00:00:00+00:00 [queued]>
[2022-01-14 20:51:23,689] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-14 20:51:23,693] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-14 20:51:23,693] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-14 20:51:24,244] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): task_01> on 2022-01-13 00:00:00+00:00
[2022-01-14 20:51:24,248] {standard_task_runner.py:52} INFO - Started process 47946 to run task
[2022-01-14 20:51:24,440] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_01', 'scheduled__2022-01-13T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmp30xg9lmj', '--error-file', '/tmp/tmp6l45csdc']
[2022-01-14 20:51:24,443] {standard_task_runner.py:77} INFO - Job 59: Subtask task_01
[2022-01-14 20:51:28,402] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_01 scheduled__2022-01-13T00:00:00+00:00 [running]> on host airflowvm
[2022-01-14 20:51:32,092] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_01
AIRFLOW_CTX_EXECUTION_DATE=2022-01-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-13T00:00:00+00:00
[2022-01-14 20:51:32,094] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-14 20:51:32,097] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-01-14 20:51:32,450] {subprocess.py:85} INFO - Output:
[2022-01-14 20:51:35,550] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-14 20:51:37,745] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_01, execution_date=20220113T000000, start_date=20220114T205123, end_date=20220114T205137
[2022-01-14 20:51:42,697] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-14 20:51:46,040] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
