[2022-01-05 20:32:39,076] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_02 manual__2022-01-05T20:31:56.285182+00:00 [queued]>
[2022-01-05 20:32:39,110] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_02 manual__2022-01-05T20:31:56.285182+00:00 [queued]>
[2022-01-05 20:32:39,110] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-05 20:32:39,110] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-05 20:32:39,110] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-05 20:32:39,128] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): task_02> on 2022-01-05 20:31:56.285182+00:00
[2022-01-05 20:32:39,129] {standard_task_runner.py:52} INFO - Started process 10450 to run task
[2022-01-05 20:32:39,161] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_02', 'manual__2022-01-05T20:31:56.285182+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmp6617bxzs', '--error-file', '/tmp/tmpuq2d508v']
[2022-01-05 20:32:39,164] {standard_task_runner.py:77} INFO - Job 27: Subtask task_02
[2022-01-05 20:32:39,511] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_02 manual__2022-01-05T20:31:56.285182+00:00 [running]> on host airflowvm
[2022-01-05 20:32:39,921] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_02
AIRFLOW_CTX_EXECUTION_DATE=2022-01-05T20:31:56.285182+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-05T20:31:56.285182+00:00
[2022-01-05 20:32:39,922] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-05 20:32:39,922] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-01-05 20:32:39,936] {subprocess.py:85} INFO - Output:
[2022-01-05 20:32:42,965] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-05 20:32:43,214] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_02, execution_date=20220105T203156, start_date=20220105T203239, end_date=20220105T203243
[2022-01-05 20:32:43,410] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-05 20:32:44,217] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
