[2022-01-11 20:18:11,587] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_03 scheduled__2022-01-07T00:00:00+00:00 [queued]>
[2022-01-11 20:18:11,771] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_03 scheduled__2022-01-07T00:00:00+00:00 [queued]>
[2022-01-11 20:18:11,771] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 20:18:11,771] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-11 20:18:11,771] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 20:18:12,004] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): task_03> on 2022-01-07 00:00:00+00:00
[2022-01-11 20:18:12,088] {standard_task_runner.py:52} INFO - Started process 5688 to run task
[2022-01-11 20:18:12,156] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_03', 'scheduled__2022-01-07T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmpdf0nosni', '--error-file', '/tmp/tmpofb2609x']
[2022-01-11 20:18:12,233] {standard_task_runner.py:77} INFO - Job 49: Subtask task_03
[2022-01-11 20:18:17,398] {local_task_job.py:211} WARNING - State of this instance has been externally set to None. Terminating instance.
[2022-01-11 20:18:17,501] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 5688. PIDs of all processes in the group: [5688]
[2022-01-11 20:18:17,503] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 5688
[2022-01-11 20:18:17,530] {process_utils.py:70} INFO - Process psutil.Process(pid=5688, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='20:18:12') (5688) terminated with exit code Negsignal.SIGTERM
