[2022-01-11 20:18:06,325] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_03 scheduled__2022-01-09T00:00:00+00:00 [queued]>
[2022-01-11 20:18:06,487] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_03 scheduled__2022-01-09T00:00:00+00:00 [queued]>
[2022-01-11 20:18:06,498] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 20:18:06,498] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-11 20:18:06,516] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 20:18:06,626] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): task_03> on 2022-01-09 00:00:00+00:00
[2022-01-11 20:18:06,642] {standard_task_runner.py:52} INFO - Started process 5400 to run task
[2022-01-11 20:18:06,682] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_03', 'scheduled__2022-01-09T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmpjmewuiw0', '--error-file', '/tmp/tmpt8qm9kb8']
[2022-01-11 20:18:06,691] {standard_task_runner.py:77} INFO - Job 48: Subtask task_03
[2022-01-11 20:18:11,543] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_03 scheduled__2022-01-09T00:00:00+00:00 [running]> on host airflowvm
[2022-01-11 20:18:12,477] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_03
AIRFLOW_CTX_EXECUTION_DATE=2022-01-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-09T00:00:00+00:00
[2022-01-11 20:18:12,478] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-11 20:18:12,502] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-01-11 20:18:12,575] {subprocess.py:85} INFO - Output:
[2022-01-11 20:18:15,628] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-11 20:18:15,841] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_03, execution_date=20220109T000000, start_date=20220111T201806, end_date=20220111T201815
[2022-01-11 20:18:15,962] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-11 20:18:16,089] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
