[2022-01-04 21:06:25,641] {taskinstance.py:1022} INFO - Dependencies not met for <TaskInstance: parallel_dag.task_01 scheduled__2022-01-03T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-01-04 21:06:25,671] {local_task_job.py:99} INFO - Task is not able to be run
